name: Publish Docker image

on:
  push:
    branches: ['master']

jobs:
  build_and_deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Install MySQL Client
        run: sudo apt-get install mysql-client

      - name: Install Composer
        run: |
          php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
          php composer-setup.php
          php -r "unlink('composer-setup.php');"
          mv composer.phar /usr/local/bin/composer

      
      - name: Log in to Docker Hub
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          username: ${{secrets.Dusername}}
          password: ${{secrets.Dpassword}}
      
      - name: Build Docker Image
        run: docker build -t book_collection .
        
      - name: Tag Docker Image
        run: docker tag book_collection:latest ${{secrets.Dusername}}/book_collection:latest
      
      - name: Push Docker Image
        run: docker push ${{secrets.Dusername}}/book_collection:latest

      - name: Run Docker Container
        run: docker run -d -p 80:80 ${{secrets.Dusername}}/book_collection:latest
