name: Publish Docker image

on:
  push:
    branches: ['master']

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
      
      - name: Log in to Docker Hub
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          username: ${{secrets.Dusername}}
          password: ${{secrets.Dpassword}}
      
      - name: Build Docker Image
        run: docker build -t book_collection .
        
      - name: Tag Docker Image
        run: docker tag book_collection:latest revu024/book_collection:latest
      
      - name: Push Docker Image
        run: docker push revu024/book_collection:latest

      - name: Run Docker Container
        run: docker run -d -p 80:80 revu024/book_collection:latest   
