name: PHP CI

on: [push]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.0'
        tools: package, phpunit
    - name: Validate package.json and package.lock
      run: package validate
    - name: Install dependencies
      run: package install --prefer-dist --no-progress --no-suggest
    - name: Run tests
      run: vendor/bin/phpunit
