name: Continuous Integration

on:
  pull_request:
    branches: [master]

jobs:
  #test_pull_request:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install PHP
        run: sudo apt-get update && sudo apt-get install -y php
      - name: Install Composer
        run: curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
      - name: Install Dependencies
        run: composer install
      - name: Run Tests
        run: phpunit
      - name: Build
        run: php your-build-script.php
